builds:
  - binary: minecraft
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: minecraft
    homepage: "https://github.com/mericozkayagan/minecraft"
    tap:
      owner: mericozkayagan
      name: homebrew-mericozkayagan
    commit_author:
      name: mericozkayagan
      email: mericozkayagan@gmail.com
